#!/bin/bash -ex
trunk build
git add docs/

# Read the commit message temporary file
commit_message=$(cat .git/COMMIT_EDITMSG)

# Check if the commit message contains one or more line breaks
if [[ "$commit_message" == *$'\n'* ]]; then
	echo "Multi-line commit messages are forbidden! Try committing again."
	exit 1
fi
